In [26]:
import os
import torch
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from EPInformer.models import EPInformer_v2

In [27]:
os.chdir('/home/witoslaw/diffTSS/data/RNASeq_bw/')

In [28]:
rna = pd.read_csv('K562.minus.ENCFF528VFJ.coverage.txt', sep='\t', header=None)
rna

,0,1,2,3,4,5,6,7,8,9
0,chr1,28359,30359,ENSG00000310526,0,-,chr1,28360,28361,0.18965
1,chr1,28359,30359,ENSG00000310526,0,-,chr1,28361,28362,0.18965
2,chr1,28359,30359,ENSG00000310526,0,-,chr1,28362,28363,0.18769
3,chr1,28359,30359,ENSG00000310526,0,-,chr1,28363,28364,0.18769
4,chr1,28359,30359,ENSG00000310526,0,-,chr1,28364,28365,0.18416
...,...,...,...,...,...,...,...,...,...,...
9602711,chrY,13702902,13704902,ENSG00000290853,0,+,chrY,13703512,13703513,0.00392
9602712,chrY,13702902,13704902,ENSG00000290853,0,+,chrY,13703513,13703514,0.00392
9602713,chrY,13702902,13704902,ENSG00000290853,0,+,chrY,13703514,13703515,0.00392
9602714,chrY,13702902,13704902,ENSG00000290853,0,+,chrY,13703515,13703516,0.00392
9602715,chrY,13702902,13704902,ENSG00000290853,0,+,chrY,13703516,13703517,0.00392

In [44]:
rna9 = rna[9].apply(lambda x: np.log10(1+(x))
rna9

0          0.075419
1          0.075419
2          0.074703
3          0.074703
4          0.073410
             ...
9602711    0.001699
9602712    0.001699
9602713    0.001699
9602714    0.001699
9602715    0.001699
Name: 9, Length: 9602716, dtype: float64

3.091572000243601

In [10]:
rna[9] = rna[9].apply(np.log10)
rna[9]

0         -0.722047
1         -0.722047
2         -0.726559
3         -0.726559
4         -0.734805
             ...
9602711   -2.406714
9602712   -2.406714
9602713   -2.406714
9602714   -2.406714
9602715   -2.406714
Name: 9, Length: 9602716, dtype: float64

In [11]:
rna[9].max()

3.0912201253858664

In [12]:
rna[9].min()

-3.3565473235138126

In [13]:
rna[9] = rna[9] / 4
rna[9]

0         -0.180512
1         -0.180512
2         -0.181640
3         -0.181640
4         -0.183701
             ...
9602711   -0.601678
9602712   -0.601678
9602713   -0.601678
9602714   -0.601678
9602715   -0.601678
Name: 9, Length: 9602716, dtype: float64

In [14]:
rna[9].max()

0.7728050313464666

In [15]:
rna[9].min()

-0.8391368308784531

In [16]:
rna.to_csv('K562.minus.ENCFF528VFJ.coverage.log10.txt', sep='\t', header=None, index=None)

In [17]:
os.getcwd()

'/home/witoslaw/diffTSS/data/RNASeq_bw'

In [18]:
rna = pd.read_csv('GM12878.minus.ENCFF078ATR.coverage.txt', sep='\t', header=None)
rna

,0,1,2,3,4,5,6,7,8,9
0,chr1,28359,30359,ENSG00000310526,0,-,chr1,28359,28360,0.19849
1,chr1,28359,30359,ENSG00000310526,0,-,chr1,28360,28361,0.19849
2,chr1,28359,30359,ENSG00000310526,0,-,chr1,28361,28362,0.19849
3,chr1,28359,30359,ENSG00000310526,0,-,chr1,28362,28363,0.19849
4,chr1,28359,30359,ENSG00000310526,0,-,chr1,28363,28364,0.19849
...,...,...,...,...,...,...,...,...,...,...
5043083,chrY,11214005,11216005,ENSG00000291032,0,-,chrY,11214996,11214997,0.00393
5043084,chrY,11214005,11216005,ENSG00000291032,0,-,chrY,11214997,11214998,0.00393
5043085,chrY,11214005,11216005,ENSG00000291032,0,-,chrY,11214998,11214999,0.00393
5043086,chrY,11214005,11216005,ENSG00000291032,0,-,chrY,11214999,11215000,0.00393
5043087,chrY,11214005,11216005,ENSG00000291032,0,-,chrY,11215000,11215001,0.00393

In [19]:
rna[9] = rna[9].apply(np.log10)
rna[9]

0         -0.702261
1         -0.702261
2         -0.702261
3         -0.702261
4         -0.702261
             ...
5043083   -2.405607
5043084   -2.405607
5043085   -2.405607
5043086   -2.405607
5043087   -2.405607
Name: 9, Length: 5043088, dtype: float64

In [20]:
rna[9].max()

3.0918322042159287

In [21]:
rna[9].min()

-3.1023729087095586

In [22]:
rna[9] = rna[9] / 4

In [23]:
rna[9].max()

0.7729580510539822

In [24]:
rna[9].min()

-0.7755932271773897

In [25]:
rna.to_csv('GM12878.minus.ENCFF078ATR.coverage.log10.txt', sep='\t', header=None, index=None)